packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "first-ami"
  instance_type = "t2.micro"
  source_ami    = "ami-0e83be366243f524a"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt update", "sudo apt install nginx -y"]
  }

}
