packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
  }
}

variable "description" {
  type = string
}

variable "version" {
  type = string
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "${var.description}-${var.version}"
  instance_type = "t2.micro"
  source_ami    = "ami-0e83be366243f524a"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "setup.sh"
  }

  provisioner "file" {
    destination = "/tmp/"
    source      = "index.html"
  }

  provisioner "shell" {
    inline = ["sudo mv /tmp/index.html /var/www/html/"]
  }

  post-processor "manifest" {
    output = "${var.description}.json"
  }
  post-processor "vagrant" {
  }
}
